import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from '@/components/nav/nav'
import React from 'react'
import Logo from "../app/../../public/Logo.svg"
import Footer from "@/components/footer/Footer";

export const navListName = [
  { navListName: "About us", url: "/aboutus" },
  { navListName: "Projects", url: "/projects" },
  { navListName: "Services", url: "/services" },
  { navListName: "Teams", url: "/teams" },
  { navListName: "Contact", url: "/contact" },
];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Swedy Archei",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar leftside={Logo} rightside={navListName} />
        {children}
        <Footer />
        
        </body>
    </html>
  );
}
